GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 19734]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
_PyObject_IS_GC (obj=0x74b841d8a810) at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:452

Stack backtrace
---------------
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:452
No locals.
#1  visit_decref (parent=0x74b841d75360, op=0x74b841d8a810)
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:456
        gc = <optimized out>
#2  func_traverse (f=0x74b841d75360, visit=0x4e2400 <visit_decref>, 
    arg=0x74b841d75360)
    at /usr/local/src/conda/python-3.10.14/Objects/funcobject.c:662
        vret = <optimized out>
#3  0x00000000004e209f in subtract_refs (containers=<optimized out>)
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:482
        op = 0x74b841d75360
        traverse = <optimized out>
        gc = 0x74b841d75350
#4  deduce_unreachable (base=base@entry=0x1d13610, 
    unreachable=unreachable@entry=0x7ffc38120ee0)
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:1105
No locals.
#5  0x00000000004e1813 in gc_collect_main (tstate=0x1d2f3f0, generation=2, 
    n_collected=0x7ffc38120fc0, n_uncollectable=0x7ffc38120fb8, nofail=0)
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:1239
        i = 2
        m = 0
        n = 0
        young = 0x1d13610
        old = 0x1d13610
        unreachable = {_gc_next = 128334736512976, _gc_prev = 8195}
        finalizers = {_gc_next = 30602224, _gc_prev = 5941841}
        gc = <optimized out>
        t1 = 0
        gcstate = 0x1d135c8
        final_unreachable = {_gc_next = 128334742913616, _gc_prev = 5069479}
        stats = <optimized out>
#6  0x00000000005915bc in gc_collect_with_callback (
    tstate=tstate@entry=0x1d2f3f0, generation=generation@entry=2)
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:1413
        result = <optimized out>
        collected = 128334744729808
        uncollectable = 5344818
#7  0x00000000005c6573 in PyGC_Collect ()
    at /usr/local/src/conda/python-3.10.14/Modules/gcmodule.c:2099
        exc = 0x0
        value = 0x0
        tb = 0x0
        tstate = 0x1d2f3f0
        gcstate = 0x1d135c8
        n = <optimized out>
#8  0x00000000005c5fc6 in Py_FinalizeEx ()
    at /usr/local/src/conda/python-3.10.14/Python/pylifecycle.c:1784
        status = <optimized out>
        runtime = 0x7538c0 <_PyRuntime>
        tstate = 0x1d2f3f0
        malloc_stats = 0
#9  0x00000000005b7dd9 in Py_RunMain ()
    at /usr/local/src/conda/python-3.10.14/Modules/main.c:672
        exitcode = 1
#10 0x0000000000588679 in Py_BytesMain (argc=<optimized out>, 
    argv=<optimized out>)
    at /usr/local/src/conda/python-3.10.14/Modules/main.c:1090
        args = {argc = 4, use_bytes_argv = 1, bytes_argv = 0x7ffc381212c8, 
          wchar_argv = 0x0}
#11 0x000074b842e29d90 in __libc_start_call_main (
    main=main@entry=0x588630 <main>, argc=argc@entry=4, 
    argv=argv@entry=0x7ffc381212c8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -1380257288205198408, 
                140721249194696, 5801520, 0, 128334749683776, 
                1378144826732223416, 407807256816688056}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffc381212c8, 
              0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 940708552}}}
        not_first_call = <optimized out>
#12 0x000074b842e29e40 in __libc_start_main_impl (main=0x588630 <main>, 
    argc=4, argv=0x7ffc381212c8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffc381212b8)
    at ../csu/libc-start.c:392
No locals.
#13 0x000000000058852e in _start ()
No symbol table info available.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Inferior 1 (process 19726) detached]
452	/usr/local/src/conda/python-3.10.14/Modules/gcmodule.c: No such file or directory.
Traceback (most recent call last):
  File "<string>", line 25, in <module>
ModuleNotFoundError: No module named 'Cython'
Error while executing Python code.
